//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyvinvointisovellus
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kirjautuminen
    {
        public int KirjautumisID { get; set; }
        [Required(ErrorMessage = "Anna käyttäjätunnus!")]
        public string Kayttajatunnus { get; set; }
        [Required(ErrorMessage = "Anna salasana!")]
        public string Salasana { get; set; }
        public Nullable<int> KayttajaID { get; set; }

        public virtual Kayttajat Kayttajat { get; set; }
        public string LoginErrorMessage { get; set; }
        public string Postitoimipaikka { get; set; }
    }
}