//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyvinvointisovellus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postitoimipaikat
    {
        public int Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
    }
}
