//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyvinvointisovellus.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD:Models/sysdiagrams.cs
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
=======
    public partial class Postitoimipaikat
    {
        public int Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
>>>>>>> f2fc6a154a9091b52151f7f6549fdafe2ea1728b:Postitoimipaikat.cs
    }
}
