//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyvinvointisovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kommentit
    {
        public int KommenttiID { get; set; }
        public string Kommentti { get; set; }
        public Nullable<System.DateTime> Pvm { get; set; }
        public Nullable<int> PalauteID { get; set; }
        public Nullable<int> KayttajaID { get; set; }
    
        public virtual Kayttajat Kayttajat { get; set; }
        public virtual Palaute Palaute { get; set; }
    }
}
